PROJ = reqwalker_top
SIM_MODULE = reqwalker

ADD_SRC = reqwalker.v

ADD_CLEAN_FOLDER = reqwalker_cvr reqwalker_prf

PIN_DEF = ../icebreaker/icebreaker.pcf
DEVICE = up5k
PACKAGE = sg48 
include ../main.mk
