PROJ = helloworld
SIM_MODULE = helloworld

ADD_SRC = txuart/txuart.v

ADD_CLEAN_FOLDER = txuart_cvr txuart_prf

PIN_DEF = ../icebreaker/icebreaker.pcf
DEVICE = up5k
PACKAGE = sg48 
include ../main.mk
